"""empty message

Revision ID: 9368709dd7cb
Revises: 
Create Date: 2020-04-23 18:04:21.413974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9368709dd7cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donut', sa.Column('img_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donut', 'img_url')
    # ### end Alembic commands ###
